CREATE TABLE TEST_DOMAIN(
	TestDomainID	CHAR(6)			NOT NULL,
	CONSTRAINT 		TESTDOMAINID_PK 		PRIMARY KEY(TestDomainID)
	); 
  
CREATE TABLE TEST(
	TestID			CHAR(8)			NOT NULL,
	TestDomainID	CHAR(6)			NOT NULL,
    PublisherID		CHAR(8),
    TestTimeLimit	INT,
	CONSTRAINT 		TESTID_PK 		PRIMARY KEY(TestID),
	CONSTRAINT 		TESTDOMAINID_FK 			FOREIGN KEY(TestDomainID)
						REFERENCES TEST_DOMAIN(TestDomainID)
							ON UPDATE NO ACTION
							ON DELETE NO ACTION
	);

CREATE TABLE PROBLEM_TYPE(
	ProblemTypeID	CHAR(30)		NOT NULL,
    TestDomainID 	CHAR(6)			NOT NULL,
	CONSTRAINT 		PROBLEMTYPEID_PK 	PRIMARY KEY(ProblemTypeID),
	CONSTRAINT 		TESTDOMAINID1_FK 			FOREIGN KEY(TestDomainID)
						REFERENCES TEST_DOMAIN(TestDomainID)
							ON UPDATE NO ACTION
							ON DELETE NO ACTION
	);

CREATE TABLE PROBLEM(
	ProblemID		CHAR(8)			NOT NULL,
	TestID			CHAR(8)			NOT NULL,
	ProblemTypeID	CHAR(30)		NOT NULL,
	Accuracy		double,
	MainText		Longtext		NOT NULL,
    ChoiceText1		Longtext,
    ChoiceText2		Longtext,
    ChoiceText3		Longtext,
    ChoiceText4		Longtext,
    ChoiceText5		Longtext,
    SolvingTimeAvg	Double,
    SolvingTimeStd	Double,
	CONSTRAINT 		PROBLEMID_PK 		PRIMARY KEY(ProblemID),
	CONSTRAINT 		TESTID_FK 			FOREIGN KEY(TestID)
						REFERENCES TEST(TestID)
							ON UPDATE NO ACTION
							ON DELETE NO ACTION,
	CONSTRAINT 		PROBLEMTYPEID_FK 	FOREIGN KEY(ProblemTypeID)
						REFERENCES PROBLEM_TYPE(ProblemTypeID)
							ON UPDATE NO ACTION
							ON DELETE NO ACTION
	);
    
CREATE TABLE USERS(
	UserID			CHAR(9)			NOT NULL,
	CONSTRAINT 		USERID_PK 		PRIMARY KEY(UserID)
	);
    
CREATE TABLE WEAK_OR_NOT(
	ProblemTypeID	CHAR(30)		NOT NULL,
	UserID			CHAR(9)			NOT NULL,
    WeakOrNot		Int,
	CONSTRAINT 		ALLINONE_PK 		PRIMARY KEY(ProblemTypeID, UserID),
	CONSTRAINT 		PROBLEMTYPEID1_FK 	FOREIGN KEY(ProblemTypeID)
						REFERENCES PROBLEM_TYPE(ProblemTypeID)
							ON UPDATE NO ACTION
							ON DELETE NO ACTION,
	CONSTRAINT 		USERID_FK 	FOREIGN KEY(UserID)
						REFERENCES USERS(UserID)
							ON UPDATE NO ACTION
							ON DELETE NO ACTION
	);
    
CREATE TABLE PROBLEM_FEEDBACK(
	ProblemID		CHAR(8)			NOT NULL,
	UserID			CHAR(9)			NOT NULL,
    RightWrong		Int,
    SolvingTime		INT,
	CONSTRAINT 		ALLINONE1_PK 		PRIMARY KEY(ProblemID, UserID),
	CONSTRAINT 		PROBLEMID_FK 	FOREIGN KEY(ProblemID)
						REFERENCES PROBLEM(ProblemID)
							ON UPDATE NO ACTION
							ON DELETE NO ACTION,
	CONSTRAINT 		USERID1_FK 	FOREIGN KEY(UserID)
						REFERENCES USERS(UserID)
							ON UPDATE NO ACTION
							ON DELETE NO ACTION
	);
    
CREATE TABLE TEST_FEEDBACK_TEMP(
	TestID			CHAR(8)			NOT NULL,
	UserID			CHAR(9)			NOT NULL,
    Ranking			INT,
    Score			INT,
	CONSTRAINT 		ALLINONE2_PK 		PRIMARY KEY(TestID, UserID),
	CONSTRAINT 		TESTID1_FK 			FOREIGN KEY(TestID)
						REFERENCES TEST(TestID)
							ON UPDATE NO ACTION
							ON DELETE NO ACTION,
	CONSTRAINT 		USERID2_FK 	FOREIGN KEY(UserID)
						REFERENCES USERS(UserID)
							ON UPDATE NO ACTION
							ON DELETE NO ACTION
	);